name: Pavi's Food Tales Auto Publisher

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest

    env:
      BLOG_ID: ${{ secrets.BLOG_ID }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      GOOGLE_CLIENT_SECRET_JSON: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Run RSS Reader
        run: |
          python scripts/rss_reader.py

      - name: Run Blogger API
        run: |
          python scripts/blogger_api.py
