name: Pavi's Food Tales Auto Publisher

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify Workflow
        run: echo "GitHub Actions is working successfully!"
